### ISSUE TITLE
python demo_MNIST.py can run in pytorch0.3.0,  but out of memory in pytorch 0.4.0

### ISSUE THREAD

**Issue by 853498747** [AlexHex7/Non-local_pytorch#9]
excuse me
        your code  can run in  my pytorch 0.3.0 environment.when I run your code in pytorch 0.4.0 :
### 
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1525812548180/work/aten/src/THC/generic/THCStorage.cu:58
###
but myself code need pytorch 0.4.0 ,can you give me some advice/help?

**Comment by AlexHex7** [comment]
@853498747  Is there something warning tips when you run it? In 0.4.0, you should use torch.set_grad_enabled(True) instead of Variables' parameters volatile.

**Comment by cathy0213** [comment]
@853498747 @AlexHex7 
Hi, I got the same question and I solved this problem with wrapping the test code into torch.no_grad(). Because the volatile flag is deprecated in pytorch 0.4.0.
Some context managers were introduced in pytorch 0.4.0. You can look at the [migration-guide](https://pytorch.org/2018/04/22/0_4_0-migration-guide.html) for details.

**Comment by AlexHex7** [comment]
Yes. And thanks for your sharing.
